# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - |
        go clean -testcache
        go test ./...

  gen:
    cmds:
      - go generate ./...

  build:
    cmds:
      - go build -v -o bin/abs-tract

  build:docker:
    deps: [build]
    cmds:
      - docker build . -t scyllpoesis/abs-tract:latest
      - docker push scyllpoesis/abs-tract:latest

  run:
    cmds:
      - go run .

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name abs-tract \
          -p 5555:5555 \
          scyllpoesis/abs-tract
